services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto
  api:
    image: api:latest
    profiles: ["api", "full"]
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      PYTHONNET_PYDLL: /usr/lib/x86_64-linux-gnu/libpython3.12.so
      PYTHONPATH: /app
  web:
    image: web:latest
    profiles: ["web", "full"]
    ports:
      - "3000:80"
