services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "healthcheck", "-m", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orderpickingsystem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d orderpickingsystem"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    build:
      context: ../../
      dockerfile: sources/apps/Api/Dockerfile
      target: ef
    image: migrate:latest
    profiles: ["migrate", "api", "full"]
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        cd /Api/src;
        dotnet ef database update
      "
  api:
    build:
      context: ../../
      dockerfile: sources/apps/Api/Dockerfile
      target: release
      args:
        PYTHONNET_PYDLL: ${PYTHONNET_PYDLL:-/usr/lib/x86_64-linux-gnu/libpython3.12.so}
    image: api:latest
    profiles: ["api", "full"]
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      PYTHONPATH: /app
  web:
    build:
      context: ../../
      dockerfile: sources/apps/Web/Dockerfile
      target: release
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080/}
    image: web:latest
    profiles: ["web", "full"]
    ports:
      - "3000:80"
  alphabot-simulator:
    build:
      context: ../../
      dockerfile: sources/apps/AlphaBot/Dockerfile
      target: release
    image: alphabot-simulator:latest
    profiles: ["simulator"]
    depends_on:
      mqtt-broker:
        condition: service_healthy

volumes:
  postgres_data: