services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto
  db:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orderpickingsystem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  api:
    image: api:latest
    profiles: ["api", "full"]
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      PYTHONPATH: /app
  web:
    image: web:latest
    profiles: ["web", "full"]
    ports:
      - "3000:80"

volumes:
  postgres_data: