// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Database.Migrations
{
    [DbContext(typeof(OrderPickingDbContext))]
    [Migration("20260406192244_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Orders.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double?>("FinishPickingTime")
                        .HasColumnType("double precision");

                    b.Property<double>("StartPickingTime")
                        .HasColumnType("double precision");

                    b.Property<double>("Timestamp")
                        .HasColumnType("double precision");

                    b.Property<int>("TspAlgorithm")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Api.Orders.Order", b =>
                {
                    b.OwnsMany("Api.Orders.OrderedProduct", "OrderedProducts", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("Orders_OrderedProducts");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Api.RobotOperations.Position", "Position", b2 =>
                                {
                                    b2.Property<Guid>("OrderedProductOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("OrderedProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("X")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Y")
                                        .HasColumnType("integer");

                                    b2.HasKey("OrderedProductOrderId", "OrderedProductId");

                                    b2.ToTable("Orders_OrderedProducts");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderedProductOrderId", "OrderedProductId");
                                });

                            b1.Navigation("Position")
                                .IsRequired();
                        });

                    b.OwnsMany("Api.Orders.OrderedProduct", "PickedProducts", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("Orders_PickedProducts");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Api.RobotOperations.Position", "Position", b2 =>
                                {
                                    b2.Property<Guid>("OrderedProductOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("OrderedProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("X")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Y")
                                        .HasColumnType("integer");

                                    b2.HasKey("OrderedProductOrderId", "OrderedProductId");

                                    b2.ToTable("Orders_PickedProducts");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderedProductOrderId", "OrderedProductId");
                                });

                            b1.Navigation("Position")
                                .IsRequired();
                        });

                    b.Navigation("OrderedProducts");

                    b.Navigation("PickedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
