// <auto-generated />
using System;
using System.Collections.Generic;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Database.Migrations
{
    [DbContext(typeof(OrderPickingDbContext))]
    [Migration("20260606164242_AddedTspPositionOrderNumber")]
    partial class AddedTspPositionOrderNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Orders.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("DerivativeAbsoluteMean")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<double>>("DerivativeHistory")
                        .HasColumnType("double precision[]");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<long?>("FinishPickingTime")
                        .HasColumnType("bigint");

                    b.Property<double?>("IntegralAbsoluteMean")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<double>>("IntegralHistory")
                        .HasColumnType("double precision[]");

                    b.Property<double?>("PowerDifferenceAbsoluteMean")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<double>>("PowerDifferenceHistory")
                        .HasColumnType("double precision[]");

                    b.Property<double?>("ProportionalAbsoluteMean")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<double>>("ProportionalHistory")
                        .HasColumnType("double precision[]");

                    b.Property<long?>("StartPickingTime")
                        .HasColumnType("bigint");

                    b.Property<double>("Timestamp")
                        .HasColumnType("double precision");

                    b.Property<int>("TspAlgorithm")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Api.RobotOperations.TspPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TspAlgorithmResultId")
                        .HasColumnType("uuid");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TspAlgorithmResultId");

                    b.ToTable("TspPosition");
                });

            modelBuilder.Entity("Api.TravelingSalesmanAlgorithms.TspAlgorithmResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<double>>("Distances")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalWeight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("TspAlgorithmResult");
                });

            modelBuilder.Entity("Api.Orders.Order", b =>
                {
                    b.OwnsMany("Api.Orders.OrderedProduct", "OrderedProducts", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("Orders_OrderedProducts");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Api.RobotOperations.Position", "Position", b2 =>
                                {
                                    b2.Property<Guid>("OrderedProductOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("OrderedProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("X")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Y")
                                        .HasColumnType("integer");

                                    b2.HasKey("OrderedProductOrderId", "OrderedProductId");

                                    b2.ToTable("Orders_OrderedProducts");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderedProductOrderId", "OrderedProductId");
                                });

                            b1.Navigation("Position")
                                .IsRequired();
                        });

                    b.OwnsMany("Api.Orders.OrderedProduct", "PickedProducts", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("Orders_PickedProducts");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Api.RobotOperations.Position", "Position", b2 =>
                                {
                                    b2.Property<Guid>("OrderedProductOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("OrderedProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("X")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Y")
                                        .HasColumnType("integer");

                                    b2.HasKey("OrderedProductOrderId", "OrderedProductId");

                                    b2.ToTable("Orders_PickedProducts");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderedProductOrderId", "OrderedProductId");
                                });

                            b1.Navigation("Position")
                                .IsRequired();
                        });

                    b.Navigation("OrderedProducts");

                    b.Navigation("PickedProducts");
                });

            modelBuilder.Entity("Api.RobotOperations.TspPosition", b =>
                {
                    b.HasOne("Api.TravelingSalesmanAlgorithms.TspAlgorithmResult", null)
                        .WithMany("Path")
                        .HasForeignKey("TspAlgorithmResultId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.TravelingSalesmanAlgorithms.TspAlgorithmResult", b =>
                {
                    b.HasOne("Api.Orders.Order", null)
                        .WithOne("TspAlgorithmResults")
                        .HasForeignKey("Api.TravelingSalesmanAlgorithms.TspAlgorithmResult", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Orders.Order", b =>
                {
                    b.Navigation("TspAlgorithmResults");
                });

            modelBuilder.Entity("Api.TravelingSalesmanAlgorithms.TspAlgorithmResult", b =>
                {
                    b.Navigation("Path");
                });
#pragma warning restore 612, 618
        }
    }
}
